In [2]:
import numpy as np

In [3]:
python_list = list(range(10,30,5))       

In [4]:
arr1= np.array([5,12,8,33])     # np.array(list) convert list into array


In [5]:
type(arr1)

numpy.ndarray

In [6]:
np.shape(arr1)    # shape of array 1D, 2D, 3D

(4,)

In [7]:
np.size(arr1)     # length of array

4

In [8]:
arr1.ndim       # dimension of array

1

Comparision between list and array execution time

In [9]:
python_list = list(range(1000000))
numpy_array = np.arange(1000000)       

In [10]:
%time for i in range(100): results=[i*5 for i in python_list]

Wall time: 10.9 s


In [11]:
%time for i in range(100): results=5* numpy_array

Wall time: 237 ms


In [12]:
#Numpy array creation methods

In [13]:
a= np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
one_d_array = np.zeros(10)
one_d_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
one_d_array=np.ones(10)
one_d_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
one_d_array*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [17]:
x=np.zeros(10)
x=x+5
x

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [18]:
a= list(range(10))               # creating list and then change to array
print(a)
b= np.array(a)
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x= np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
x=np.zeros((2,3,2))      # depth, rows, columns
x

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
x.shape

(2, 3, 2)

In [22]:
arr2d=np.array([[2,4,7],[5,10,15],[11,22,33]])
arr2d

array([[ 2,  4,  7],
       [ 5, 10, 15],
       [11, 22, 33]])

In [23]:
np.shape(arr2d)

(3, 3)

In [24]:
np.size(arr2d)

9

In [25]:
arr2d.ndim

2

In [26]:
#arr2d= np.arange(10).reshape(2,5)
arr2d= np.arange(10).reshape(5,2)
#arr2d= np.arange(10).reshape(1,10)

arr2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
arr2d.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr2d.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x=x.reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
y=x.ravel()
y


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
y.base     # ravel returns just the view therefore base is original array x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
z=x.flatten()    
z


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
z.base     # flatten returns the copy from the original array therefore base is none

In [35]:
arr = np.array(5)
arr

array(5)

In [36]:
arr.ndim

0

In [37]:
arr = np.array([10])
arr

array([10])

In [38]:
arr = np.array([[10]])
arr
#arr.ndim

array([[10]])

In [39]:
arr3d=np.arange(40).reshape(4,5,2)
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [40]:
arr2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
arr2d[2,1]

5

In [42]:
arr3d[3][0][1]

31

In [43]:
arr2d[0:3]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [44]:
arr2d[0:3,1]

array([1, 3, 5])

In [45]:
x= np.arange(5,15)
x


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
x[[3,5]] #Fancy indexing

array([ 8, 10])

In [47]:
#Vectorized operations

In [48]:
x= np.arange(5,15)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
x*10

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [50]:
y=x/5
y

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [51]:
z=np.arange(10,20)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
x+z

array([15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [53]:
x*y

array([ 5. ,  7.2,  9.8, 12.8, 16.2, 20. , 24.2, 28.8, 33.8, 39.2])

In [54]:
a= np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [55]:
b= np.arange(20).reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [56]:
a@b          # martix multiplication

array([[120, 130, 140, 150],
       [320, 355, 390, 425],
       [520, 580, 640, 700],
       [720, 805, 890, 975]])

In [57]:
c= np.arange(20,40).reshape(4,5)
c

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [58]:
a*c        # multiplication by element

array([[  0,  21,  44,  69,  96],
       [125, 156, 189, 224, 261],
       [300, 341, 384, 429, 476],
       [525, 576, 629, 684, 741]])

In [59]:
c

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

## Return a value or slicing 

In [60]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
a[2,4]

14

In [62]:
a[1:4 ,2:4]

array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [63]:
a[1:4 ,2]

array([ 7, 12, 17])

In [ ]:
#Comparion between metrices

In [64]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [65]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [66]:
a>10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [67]:
b=np.where(a>2, 0, 1)
b

array([[1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [68]:
a[(a%2==0) | (a%7==0)]

array([ 0,  2,  4,  6,  7,  8, 10, 12, 14, 16, 18])

In [69]:
np.concatenate((a,b), axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 1,  1,  1,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [70]:
np.concatenate((a,b), axis=1)

array([[ 0,  1,  2,  3,  4,  1,  1,  1,  0,  0],
       [ 5,  6,  7,  8,  9,  0,  0,  0,  0,  0],
       [10, 11, 12, 13, 14,  0,  0,  0,  0,  0],
       [15, 16, 17, 18, 19,  0,  0,  0,  0,  0]])

In [71]:
np.stack((a,b))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 1,  1,  1,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]]])

In [72]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4,  1,  1,  1,  0,  0],
       [ 5,  6,  7,  8,  9,  0,  0,  0,  0,  0],
       [10, 11, 12, 13, 14,  0,  0,  0,  0,  0],
       [15, 16, 17, 18, 19,  0,  0,  0,  0,  0]])

In [73]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 1,  1,  1,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [245]:
np.r_[a,b] #concatenate axis = 0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 1,  1,  1,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [246]:
np.c_[a,b] #concatenate axis = 1

array([[ 0,  1,  2,  3,  4,  1,  1,  1,  0,  0],
       [ 5,  6,  7,  8,  9,  0,  0,  0,  0,  0],
       [10, 11, 12, 13, 14,  0,  0,  0,  0,  0],
       [15, 16, 17, 18, 19,  0,  0,  0,  0,  0]])

In [74]:
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Football ground
#### 00000
#### 11111
#### 00000
#### 11111
#### 00000
#### 11111

In [76]:
template=np.zeros((6,6))
template

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [80]:

for r in range(6):
    for c in range(6):
        if (r%2)==0:
            template[r,c]=0
        else:
            template[r,c]=1


template

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.]])

# Cross pattern

### 01110
### 10101
### 11011
### 10101
### 01110

In [145]:
template=np.ones((5,5))
template

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [156]:

for r in range(5):
    for c in range(5):
        if r==c:
            template[r,c]=0
            template[r,-c-1]=0
        

template

array([[0., 1., 1., 1., 0.],
       [1., 0., 1., 0., 1.],
       [1., 1., 0., 1., 1.],
       [1., 0., 1., 0., 1.],
       [0., 1., 1., 1., 0.]])

In [157]:
np.empty((9,9)) #Random/ arbitrary values

array([[1.08310999e-311, 1.08310999e-311, 1.08310999e-311,
        1.08310999e-311, 1.08310999e-311, 1.08310999e-311,
        1.08310999e-311, 1.08310999e-311, 1.08310999e-311],
       [1.08310999e-311, 1.08310999e-311, 1.08310999e-311,
        1.08310999e-311, 1.08310999e-311, 1.08310999e-311,
        1.08310999e-311, 1.08310999e-311, 1.08310999e-311],
       [1.08310999e-311, 1.08310999e-311, 1.08310999e-311,
        1.08310999e-311, 1.08310999e-311, 1.08310999e-311,
        1.08310999e-311, 1.08310999e-311, 1.08310999e-311],
       [1.08310999e-311, 1.08310999e-311, 1.08310999e-311,
        1.08310999e-311, 1.08310854e-311, 1.08310999e-311,
        1.08310999e-311, 1.08310999e-311, 5.37347041e-308],
       [1.08312238e-311, 1.08312238e-311, 1.08310999e-311,
        1.08310999e-311, 1.08310999e-311, 1.08310999e-311,
        1.08310999e-311, 1.08310999e-311, 1.08310999e-311],
       [1.08310999e-311, 1.08310999e-311, 1.08310999e-311,
        1.08310999e-311, 1.08310999e-311, 1.0831099

In [159]:
x=np.array([ 1,  8,  9, 10, 11])
x


array([ 1,  8,  9, 10, 11])

In [160]:
x.dtype

dtype('int32')

In [166]:
y= np.sin(x)
y

array([ 0.84147098,  0.98935825,  0.41211849, -0.54402111, -0.99999021])

In [164]:
np.floor(y)

array([ 0.,  0.,  0., -1., -1.])

In [170]:
np.rint(y)   # round value to nearest integer

array([ 1.,  1.,  0., -1., -1.])

In [167]:
np.abs(y)    # returns absolute value

array([0.84147098, 0.98935825, 0.41211849, 0.54402111, 0.99999021])

In [168]:
np.sqrt(x)

array([1.        , 2.82842712, 3.        , 3.16227766, 3.31662479])

In [169]:
np.isnan(x)     # returns bolean array either each value is NaN

array([False, False, False, False, False])

In [171]:
arr1=np.array([1,2,4,5])
arr2=np.array([3,4,6,7])
arr1+arr2

array([ 4,  6, 10, 12])

In [175]:
l1 = [1,2,4,5]
l2 = [3,4,6,7]

In [177]:
# adding two lists
# enumerate returns index and element
# we can write for i, e in enumerate(l1):  
sum=[]
for i,_ in enumerate(l1):           
    sum.append(l1[i]+l1[i])

print (sum)

[2, 4, 8, 10]


In [ ]:
# np.where(condition, option A, option B )

In [178]:
marks=np.array([25,70, 65, 80, 45])
x= np.where(marks>=50, "pass", "fail")
x

array(['fail', 'pass', 'pass', 'pass', 'fail'], dtype='<U4')

In [181]:
salary = np.array([10,70, 80, 50, 30])
incremented_salary = np.where(salary<50, salary*1.1, salary*1.05)
print(incremented_salary)
incremented_salary.dtype

[11.  73.5 84.  52.5 33. ]


dtype('float64')

In [182]:
arr=np.arange(1,25).reshape(8,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [183]:
arr.T               # Transpose of a matrix
#arr.transpose()

array([[ 1,  4,  7, 10, 13, 16, 19, 22],
       [ 2,  5,  8, 11, 14, 17, 20, 23],
       [ 3,  6,  9, 12, 15, 18, 21, 24]])

In [184]:
arr=np.array([5,10, 35, 6])
np.mean(arr)

14.0

In [189]:
arr.cumsum()

array([ 5, 15, 50, 56], dtype=int32)

In [190]:
arr.cumprod()

array([    5,    50,  1750, 10500], dtype=int32)

In [192]:
#Methods for boolean arrays
gender = np.array(['Male', 'Female', 'Male', 'Male', 'Male'])

In [196]:
arr[gender == 'Male']       # arr = gender == 'Male' is the same thing

arr

array([ True, False,  True,  True,  True])

In [197]:
arr.sum()

4

In [198]:
arr = gender == 'Female'
arr.sum()


1

In [199]:
arr.any()     # returns true if array contains one true value

True

In [200]:
arr.all()      # returns true if array contains all true values

False

In [202]:
arr=np.array([ 2,  4, 10, 20, 16])
arr

array([ 2,  4, 10, 20, 16])

In [203]:
arr.sort()            #shift+tab to see the help jupyter nootbook
arr

array([ 2,  4, 10, 16, 20])

In [204]:
arr[::-1]

array([20, 16, 10,  4,  2])

In [205]:
arr = np.array([1,2,4,1,6,2])

In [206]:
u = np.unique(arr)   # returns an array with unique elements

In [ ]:
#Save array

In [207]:
np.save('data',u)

In [209]:
content = np.load('data.npy')
content

array([1, 2, 4, 6])

In [ ]:
#Saving multiple arrays

In [210]:
students = np.array(["Ali","Asad","Ahmed"])
marks = np.array([30,20,60])

In [212]:
np.savez('arrays',std=students,m=marks)

In [213]:
results = np.load('arrays.npz')

In [214]:
results['std']     # returns a dictionary which contains all the arrays

array(['Ali', 'Asad', 'Ahmed'], dtype='<U5')

In [215]:
results['m']

array([30, 20, 60])

In [ ]:
# Linear Algebra Functions

In [218]:
arr=np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [219]:
arr.diagonal()

array([ 0,  5, 10, 15])

In [220]:
arr.trace()     # returns sum of diagonal element

30

In [224]:
from numpy import linalg
linalg.det(arr)

-2.9582283945787796e-30

In [225]:
linalg.eig(arr)

(array([ 3.24642492e+01, -2.46424920e+00,  1.92979794e-15, -4.09576009e-16]),
 array([[-0.11417645, -0.7327781 ,  0.54500164,  0.00135151],
        [-0.3300046 , -0.28974835, -0.68602671,  0.40644504],
        [-0.54583275,  0.15328139, -0.2629515 , -0.8169446 ],
        [-0.76166089,  0.59631113,  0.40397657,  0.40914805]]))

In [226]:
linalg.inv(np.array([[1,5],[9,8]]))

array([[-0.21621622,  0.13513514],
       [ 0.24324324, -0.02702703]])

In [227]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [228]:
linalg.qr(arr)     # used in recommendation system or image processing

(array([[ 0.        , -0.83666003,  0.48308786,  0.25812035],
        [-0.26726124, -0.47809144, -0.8365087 ,  0.01591196],
        [-0.53452248, -0.11952286,  0.22375381, -0.80618499],
        [-0.80178373,  0.23904572,  0.12966702,  0.53215267]]),
 array([[-1.49666295e+01, -1.65701970e+01, -1.81737645e+01,
         -1.97773319e+01],
        [ 0.00000000e+00, -1.19522861e+00, -2.39045722e+00,
         -3.58568583e+00],
        [ 0.00000000e+00,  0.00000000e+00, -1.71941189e-15,
         -5.12511879e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -8.82043219e-16]]))

In [229]:
linalg.svd(arr)

(array([[-0.09184212, -0.83160389,  0.52939495,  0.14050262],
        [-0.31812733, -0.44586433, -0.8105844 ,  0.20725087],
        [-0.54441254, -0.06012478,  0.03298396, -0.8360096 ],
        [-0.77069775,  0.32561478,  0.2482055 ,  0.48825611]]),
 array([3.51399637e+01, 2.27661021e+00, 8.80118491e-16, 4.41188001e-17]),
 array([[-0.42334086, -0.47243254, -0.52152422, -0.57061589],
        [ 0.72165263,  0.27714165, -0.16736932, -0.6118803 ],
        [ 0.5427818 , -0.66899815, -0.29034911,  0.41656546],
        [ 0.0734024 , -0.50243554,  0.78466387, -0.35563073]]))

In [230]:
np.random.normal(3,4,(3,3))

array([[ 6.94653286,  3.21229289, -4.53070533],
       [ 8.46924537, -1.61215973,  3.11906494],
       [ 3.00475977,  7.44351133, -0.58204675]])

In [232]:
np.random.gamma(1,2,(4,4))

array([[0.50203995, 4.09173976, 0.46315593, 5.01702804],
       [1.34046816, 1.89218002, 2.90408093, 1.46135747],
       [0.70422929, 0.41582337, 0.16837532, 2.68218542],
       [1.16431826, 0.34468669, 4.23947787, 0.64064873]])

In [233]:
np.random.seed(5)

In [234]:
np.random.rand()

0.22199317108973948

In [ ]:
#Reshaping

In [236]:
arr = np.arange(16)

In [237]:
arr.reshape((4,4),order='F') #column major order

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [238]:
arr.reshape((4,4),order='C') #row major order

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [239]:
arr = np.array([[1,8,7],[3,4,5],[9,0,1]])

In [240]:
arr.flatten()

array([1, 8, 7, 3, 4, 5, 9, 0, 1])

In [241]:
arr.ravel()

array([1, 8, 7, 3, 4, 5, 9, 0, 1])

In [244]:
arr.reshape(9)

array([1, 8, 7, 3, 4, 5, 9, 0, 1])

In [247]:
x = np.array([1,9,9,7,1,2,3])

In [248]:
np.split(x,[3, 5])

[array([1, 9, 9]), array([7, 1]), array([2, 3])]

In [249]:
l = np.arange(2,7,2)
l

array([2, 4, 6])

In [250]:
np.split(x,l)

[array([1, 9]), array([9, 7]), array([1, 2]), array([3])]